os: windows
language: node_js
node_js:
  - "12"

branches:
  only:
    - master
    - /^v.*$/

install:
  - npm ci
script:
  - npm run lint-all
  - npm run native-rebuild
  - npm run full-build-prod
  - npm run pack
  - npm run create-installer
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: 'dist/installer/*'
  skip_cleanup: true
  on:
    tags: true