name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Setup node-gyp
        run: npm install --global --production windows-build-tools
      - name: Install NPM
        run: npm ci
      - name: Lint
        run: npm run lint-all
      - name: Build
        run: |
          npm run native-rebuild
          npm run full-build-prod
          npm run pack
          npm run create-installer
