name: Selected Text Translate Build

on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Setup node-gyp
        run: npm install --global --production windows-build-tools@4.0.0 && npm config set msvs_version 2017
      - name: Install NPM
        run: npm ci
      - name: Lint
        run: npm run lint-all
      - name: Build
        run: |
          npm run native-rebuild
          npm run full-build-prod
          npm run pack
          npm run create-installer
      - uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          artifacts: "dist/installer/*"
          omitBody: true
          token: ${{ secrets.GITHUB_TOKEN }}